{{- if .Values.serviceMonitor.create -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "canary-bot.fullname" . }}-monitor
spec:
  ingress:
  - ports:
    - port: 8080
  podSelector:
    matchLabels:
    {{- include "canary-bot.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
{{- end }}
