{{- if .Values.serviceMonitor.create -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "canary-bot.labels" . | nindent 4 }}
  name: {{ include "canary-bot.serviceAccountName" . }}-monitor
type: Opaque
data:
  MONITOR_TOKEN: {{ .Values.serviceMonitor.token | b64enc | quote }}
{{- end }}
